### ISSUE TITLE
[Feature Request] New setting to stop serving by default

### ISSUE THREAD

**Issue by khacminh** [tokiedokie/reveal-markdown#11]
Hi,

The reveal server is running by default when launching the vscode. Could you please add a setting to stop serving by default.

Thanks

**Comment by khacminh** [comment]
similar issue: https://github.com/evilz/vscode-reveal/issues/497

**Comment by tokiedokie** [comment]
@khacminh sorry for the delay
I'll work on it

**Comment by tokiedokie** [comment]
@khacminh updated it
this extention doen't serve http by default
thank you for your request

**Comment by khacminh** [comment]
Thank you @tokiedokie. You're the best
